version: '3'
services:
  nginx:
   ports:
    - "80:80"
  node-container:
    build:
      context: .
      args:
       NODE_ENV: production
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_USERNAME=keerthana
      - MONGO_PASSWORD=123456789Kk
      - MONGO_PORT=27017
      - MONGO_IP=mongo
      - SESSION_SECRET=secret
    command: node index.js
  
  mongo:
    environment:
    - MONGO_INITDB_ROOT_USERNAME=keerthana
    - MONGO_INITDB_ROOT_PASSWORD=123456789Kk
    # env_file:
    #   - ./.env

