version: '3'
services:
  nginx:
   ports:
    - "80:80"
  node-container:
    build:
      context: .
      args:
       NODE_ENV: production
    environment:
      - PORT=3000
      - NODE_ENV=production
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_PORT=27017
      - MONGO_IP=mongo
      - SESSION_SECRET=secret
    command: node index.js
  
  mongo:
    environment:
    - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    # env_file:
    #   - ./.env

